In [19]:
import pandas as pd
import lxml
import numpy as np

### Read and parse data

In [4]:
approved = pd.read_xml("../data/raw/approved.xml")
approved

,Stage,Status,Collateral,ID,DecisionType,Date,IsCurrent,Rate,Amount,Term,Tier,UserCode,PreApproval,Reasons,Stipulations,SpecialConsiderations,AuditData,OtherData
0,Reviewed,Approved,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,None,None,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,None,Approved,NaN,87654321.0,System Decision,2023-08-16T09:45:00.0-07:00,True,2.875,45000.0,72.0,B,123.0,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
def read_xml(file_path: str) -> pd.DataFrame:
    # read file
    df = pd.read_xml("../data/raw/approved.xml").replace({None: np.nan})

    # set client stage
    df['Stage'] = df.iloc[0]['Stage']

    # return only last row
    return pd.DataFrame(df.iloc[-1]).T

In [16]:
counter_3 = pd.read_xml("../data/raw/counter_3_stips.xml")
counter_3

,Stage,Status,Collateral,ID,DecisionType,Date,IsCurrent,Rate,Amount,Term,Tier,UserCode,PreApproval,Reasons,Stipulations,SpecialConsiderations,AuditData,OtherData
0,Initial,Counter,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,None,None,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,None,Counter,NaN,678901.0,System Decision,2023-08-16T10:15:00.0-07:00,True,4.125,20000.0,48.0,C,456.0,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
no_stips = pd.read_xml("../data/raw/Counter_no_stipulations.xml")
no_stips

,Stage,Status,Collateral,ID,DecisionType,Date,IsCurrent,Rate,Amount,Term,Tier,UserCode,PreApproval,Reasons,Stipulations,SpecialConsiderations,AuditData,OtherData
0,Initial,Counter,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,None,None,NaN,NaN,None,None,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,None,Counter,NaN,654321.0,System Decision,2023-08-16T12:15:00.0-07:00,True,3.75,18000.0,60.0,B,567.0,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
declined = pd.read_xml("../data/raw/declined.xml")
declined

,Stage,Status,Collateral,ID,DecisionType,Date,IsCurrent,Rate,Amount,Term,Tier,UserCode,PreApproval,Reasons,Stipulations,SpecialConsiderations,AuditData,OtherData
0,Final,Declined,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,None,None,NaN,NaN,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,None,Declined,NaN,678901.0,System Decision,2023-08-16T11:15:00.0-07:00,True,0.0,0.0,0.0,NaN,789.0,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
questions_status = pd.read_csv("../data/raw/HalQuestions_StatusOnly_Test.csv")
questions_status

                                       Example Question  Hal-Answers
0     What is the current status of my loan applicat...         True
1     When can I expect a decision on my loan applic...         True
2     What additional information do you need from m...         True
3     Can I check the status of my loan application ...         True
4     Are there any updates on the progress of my lo...         True
...                                                 ...          ...
1058  Is there any feedback or comments on my loan a...         True
1059  How will I be notified about the status of my ...         True
1060  Are there any fees associated with processing ...        False
1061  Has a credit check been conducted for my loan ...        False
1062  How long does the final approval process take ...         True

[1063 rows x 2 columns]